version: "3"

networks:
  todo:

services:
  todo-list:
    image: xueqingliao/todo-list:${VER}
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     delay: 10s
    networks:
      todo:
        aliases:
          - todo-list
    ports:
      - "3000:3000"
